Controllers/InventoryController.cs
﻿using DDU.Data;
using DDU.Models;
using DDU.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Plugins;
﻿using Microsoft.AspNetCore.Mvc;


namespace DDU.Controllers
{
    public class InventoryController : Controller
    {


        private readonly ApplicationDbContext _db;
      
        public InventoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult PropertyManagement()
        {
            IEnumerable<InvSupplier> supplierModel = _db.invSupplier;

            var listOfModels = new ViewModelInventory();
            listOfModels.Suppliers = supplierModel;
            return View(listOfModels);
        }
        public IActionResult InventoryItems()
        {
            IEnumerable<InvInventoryItem> model = _db.invInventoryItem;
            return View("Property/InventoryItems/InventoryItems",model);
        }

        public IActionResult Equipment()
        {
            IEnumerable<InvEquipment> model = _db.invEquipment;
            return View("Property/Equipments/List",model);
        }
        public IActionResult AddEquipment()
        {
            return View("Property/Equipments/Create");
        }
        public IActionResult Suppliers()
        {
            IEnumerable<InvSupplier> model = _db.invSupplier;
            return View("Property/Suppliers/List",model);
        }
        public IActionResult AddSupplier()
        {
            return View("Property/Suppliers/Add");
        }
        public IActionResult EditSupplier(int Id)
        {
            InvSupplier model = _db.invSupplier.Where(e=>e.SupplierID == Id).FirstOrDefault();
            return View("Property/Suppliers/Edit", model);
        }
        public IActionResult DeleteSupplier(int Id)
        {
            InvSupplier model = _db.invSupplier.Where(e => e.SupplierID == Id).FirstOrDefault();
            return View("Property/Suppliers/Remove", model);
        }
        public IActionResult SupplierDetail(int Id)
        {
            InvSupplier model = _db.invSupplier.Where(e => e.SupplierID == Id).FirstOrDefault();
            return View("Property/Suppliers/view", model);
        }
        public IActionResult BinCard(int id)
        {
            string sid = id.ToString();
            IEnumerable<Vw_BinCard> objItemList = _db.vw_BinCard.Select(z => z).Where(s => s.ItemID == sid).ToList(); 
            return View(objItemList);
        }
        public IActionResult Index()
        {
            HttpContext.Session.Set("GRN", new List<InvInventoryItem>());
            try
            { 
                IEnumerable<Vw_Item> objItemList = _db.vw_Item.ToList();
                return View(objItemList);
            }
            catch
            {
                throw;
            }
            
        }
        public ActionResult GRN()
        {
            //String.Format("{0} {1}", @ViewBag.Registration.FirstName, @ViewBag.Registration.MiddleName)

            ViewData["employeeid"] = new SelectList(_db.employeeRegistration.ToList(), "EmployeeID", "FirstName"); 
            ViewData["vendorid"] = new SelectList(_db.invSupplier.ToList(), "SupplierID", "SupName");
            ViewData["store"] = new SelectList(_db.invStore.ToList(), "StoreID", "StoreCode");
            return View();
        }
        public ActionResult IssueVoucher()
        {
            //String.Format("{0} {1}", @ViewBag.Registration.FirstName, @ViewBag.Registration.MiddleName)
            ViewData["costCenter"] = new SelectList(_db.invCostCenter.ToList(), "CostID", "CostName");
            ViewData["employeeid"] = new SelectList(_db.employeeRegistration.ToList(), "EmployeeID", "FirstName");
            ViewData["store"] = new SelectList(_db.invStore.ToList(), "StoreID", "StoreCode");
            return View();
        }
        public ActionResult ItemReturn()
        {
           
            ViewData["costCenter"] = new SelectList(_db.invCostCenter.ToList(), "CostID", "CostName");
            ViewData["employeeid"] = new SelectList(_db.employeeRegistration.ToList(), "EmployeeID", "FirstName");
            ViewData["store"] = new SelectList(_db.invStore.ToList(), "StoreID", "StoreCode");
            return View();
        }

        public ActionResult Disposal()
        {

            ViewData["costCenter"] = new SelectList(_db.invCostCenter.ToList(), "CostID", "CostName");
            ViewData["employeeid"] = new SelectList(_db.employeeRegistration.ToList(), "EmployeeID", "FirstName");
            ViewData["store"] = new SelectList(_db.invStore.ToList(), "StoreID", "StoreCode");
            return View();
        }

        public ActionResult Count()
        {

            ViewData["costCenter"] = new SelectList(_db.invCostCenter.ToList(), "CostID", "CostName");
            ViewData["employeeid"] = new SelectList(_db.employeeRegistration.ToList(), "EmployeeID", "FirstName");
            ViewData["store"] = new SelectList(_db.invStore.ToList(), "StoreID", "StoreCode");
            return View();
        }

        public ActionResult Adjustment()
        {

            ViewData["costCenter"] = new SelectList(_db.invCostCenter.ToList(), "CostID", "CostName");
            ViewData["employeeid"] = new SelectList(_db.employeeRegistration.ToList(), "EmployeeID", "FirstName");
            ViewData["store"] = new SelectList(_db.invStore.ToList(), "StoreID", "StoreCode");
            return View();
        }

        public ActionResult ItemTransfer()
        {

            ViewData["costCenter"] = new SelectList(_db.invCostCenter.ToList(), "CostID", "CostName");
            ViewData["employeeid"] = new SelectList(_db.employeeRegistration.ToList(), "EmployeeID", "FirstName");
            ViewData["store"] = new SelectList(_db.invStore.ToList(), "StoreID", "StoreCode");
            return View();
        }

        public ActionResult GRNList()
        {
            IEnumerable<Vw_GRNList> objItemList = _db.vw_GRNList.ToList();
            return View(objItemList);
        }

        public ActionResult IssueVoucherList()
        {
            IEnumerable<Vw_ItemIssue> objItemList = _db.vw_ItemIssue.ToList();
            return View(objItemList);
        }
        public ActionResult ItemReturnList()
        {
            IEnumerable<Vw_ItemReturn> objItemList = _db.vw_ItemReturn.ToList();
            return View(objItemList);
        }

        public ActionResult CountList()
        {
            IEnumerable<Vw_Count> objItemList = _db.vw_Count.ToList();
            return View(objItemList);
        }

        public ActionResult AdjustmentList()
        {
            IEnumerable<Vw_Adjustment> objItemList = _db.vw_Adjustment.ToList();
            return View(objItemList);
        }

        public ActionResult ItemTransferList()
        {
            IEnumerable<Vw_ItemTransfer> objItemList = _db.vw_ItemTransfer.ToList();
            return View(objItemList);
        }

        public IActionResult GRNInvoice(Guid? id)
        {
            ViewGRNInvoice mymodel = new ViewGRNInvoice();
            mymodel.receive = _db.invReceive.Find(id);
            mymodel.store = _db.invStore.Find(mymodel.receive.StoreID);
            mymodel.supplier = _db.invSupplier.Find(mymodel.receive.SupplierID);
            mymodel.Registration = _db.employeeRegistration.Find(Guid.Parse(mymodel.receive.ApprovedBy));
            //mymodel.Registration = _db.employeeRegistration.Find(mymodel.receive.ApprovedBy);
            mymodel.vw_ReceiveDetail = _db.vw_ReceiveDetail.Select(z => z).Where(s => s.ReferenceNo == id).ToList();
            

            return View(mymodel);
            //return View();
        }

        public JsonResult Stockchecked(int id)
        {
            List<Vw_Item> products = new List<Vw_Item>();

            var productsFromDb = _db.vw_Item.Find(id);

            if (productsFromDb == null)
            {
                return Json("");

            }

            if (products == null)
            {

                products = new List<Vw_Item>();
            }
            else
            {
                products = HttpContext.Session.Get<List<Vw_Item>>("GRN");
                
            }
            productsFromDb.ReoredrPoint = 1;
            if (products == null)
            {

                products = new List<Vw_Item>();
            }
#pragma warning disable CS8602 // Dereference of a possibly null reference
            products.Add(productsFromDb);
#pragma warning restore CS8602 // Dereference of a possibly null reference.
            HttpContext.Session.Set("GRN", products);
            HttpContext.Session.Set("ISV", products);
            HttpContext.Session.Set("RT", products);
            HttpContext.Session.Set("DS", products);
            HttpContext.Session.Set("CO", products);
            HttpContext.Session.Set("AD", products);
            HttpContext.Session.Set("TR", products);
            return Json(products.Count());
        }

        public JsonResult textChangeF(int id, string name, double value)
        {
           
            List<InvInventoryItem> sitem = HttpContext.Session.Get<List<InvInventoryItem>>("GRN");
            var item = sitem.SingleOrDefault(x => x.ItemID.Equals(id));
 

            if (name == "Qty")
            {
                if (item != null)
                {
                    item.ReoredrPoint= decimal.Parse(value.ToString());

                    HttpContext.Session.Set("GRN", sitem); //it's must add for a set new session data
                }
            }
            else if (name == "UnitCost")
            {
                if (item != null)
                {
                    item.UnitCost = value;

                    HttpContext.Session.Set("GRN", sitem); //it's must add for a set new session data
                }

            }
 
            else
            {

            }

            return Json(item);
        }

Views/Inventory/AddEquipment.cshtml
@{
    ViewData["Title"] = "Add Equipment";
    ViewData["name"] = "propertyManagement";
    ViewData["category"] = "inventory";
}
@model InvEquipment
@section Content {
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Equipment</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="../../index.html">
                                <i class="fas fa-home"></i> Inventory
                            </a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="#" onclick="return false;">Equipment</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <strong>Add</strong> Equipment
                        </h2>
                    </div>
                    <div class="body">
                        <form method="post" enctype="multipart/form-data" action="@Url.Action("AddEquipment","Inventory")">
                            <div class="row clearfix">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <select asp-for="SectionID" class="col-12 m-t-20 p-l-0" select2">
                                                <option selected disabled>Select Section</option>
                                                @foreach (var unit in ViewData["invSection"] as List<DDU.Models.InvSection>)
                                                {
                                                    <option value="@unit.SecId">@unit.SecName</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <select asp-for="FixID" class="col-12 m-t-20 p-l-0" select2">
                                                <option selected disabled>Select Fixed Asset</option>
                                                @foreach (var unit in ViewData["invFixed"] as List<DDU.Models.InvFixedAsset>)
                                                {
                                                    <option value="@unit.FixID">@unit.FixName</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <select asp-for="SupplierID" class="col-12 m-t-20 p-l-0" select2">
                                                <option selected disabled>Select Supplier</option>
                                                @foreach (var supplier in ViewData["invSupplier"] as List<DDU.Models.InvSupplier>)
                                                {
                                                    <option value="@supplier.SupplierID">@supplier.SupName</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input asp-for="EqpCode" class="form-control" placeholder="Code" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input asp-for="EqpName" class="form-control" placeholder="Name" />
                                        </div>
                                    </div>
                                </div> 
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input asp-for="Capacity" class="form-control" placeholder="Capacity" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input asp-for="Unit" class="form-control" placeholder="Unit" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            <input asp-for="Mark" class="form-control" placeholder="Mark" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input asp-for="ModelNo" class="form-control" placeholder="Model Number" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input asp-for="SerialNo" type="text" class="form-control" placeholder="Serial Number" />
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input asp-for="ComeFrom" class="form-control" placeholder="Come From" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input asp-for="ManufactureYear" type="text" class="form-control" placeholder="Manufacture Year" />
                                    </div>
                                </div>
                            </div>
                             <div class="row clearfix">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input asp-for="DatePurchase" class="form-control" placeholder="Purchased Date" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12 p-t-20 text-center">
                                <button type="submit" class="btn btn-primary waves-effect m-r-15">Submit</button>
                                <button type="button" class="btn btn-danger waves-effect">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
    @section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Views/Inventory/AdjustmentList.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["name"] = "inventory";
    ViewData["category"] = "inventory";
}
@model IEnumerable<Vw_Adjustment>
@section Content {
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Inventory</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="#">
                                <i class="fas fa-home"></i> Inventory Management
                            </a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="#" onClick="return false;">Adjustment list</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-bs-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu float-end">
                                    <li>
                                        <a href="javascript:void(0);">Action</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">Another action</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">Something else here</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example contact_list">

                                <thead>
                                    <tr>
                                        <th></th>
                                        <th class="center"> StoreCode </th>
                                        <th class="center"> Reason </th>
                                  
                                        <th class="center"> AdjustmentDate </th>
                                        <th class="center"> AdjustedBY </th>
                                        <th class="center"> ApprovedBy </th>
                                        <th class="center"> Action </th>
                                    </tr>
                                </thead>
                                @foreach (var obj in Model)
                                {
                                    <tbody>
                                        <tr class="odd gradeX">
                                            <td class="table-img center">
                                                <a asp-controller="Inventory" asp-action="GRNInvoice" asp-route-id="@obj.AdjustmentID" )"><img src="~/images/inventory/2038147.png" alt=""></a>

                                            </td>
                                            <td class="center">@obj.StoreCode</td>
                                            <td class="center">@obj.Reason</td>
                                            <td class="center">@obj.AdjustmentDate.Value.ToString("MMM-dd-yyyy")</td>
                                            <td class="center">@obj.AdjustedBY</td>
                                         
                                            <td class="center">@obj.ApprovedBy</td>

                                            <td class="center">
                                                @* <a href="#" class="btn btn-tbl-edit">
                                        <i class="material-icons">create</i>
                                        </a>*@
                                                <form asp-action="ADDelete" asp-route-id="@obj.AdjustmentID" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                                                    <input type="hidden" asp-for="@obj.AdjustmentID" />
                                                    <button type="submit" value="Delete" class="btn btn-tbl-delete">
                                                        <i class="material-icons">delete_forever</i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>

                                    </tbody>
                                }

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Views/Inventory/CountList.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["name"] = "inventory";
    ViewData["category"] = "inventory";
}
@model IEnumerable<Vw_Count>
@section Content {
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Inventory</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="#">
                                <i class="fas fa-home"></i> Inventory Management
                            </a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="#" onClick="return false;">Item Count list</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-bs-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu float-end">
                                    <li>
                                        <a href="javascript:void(0);">Action</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">Another action</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">Something else here</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example contact_list">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th class="center"> StoreCode </th>
                                        <th class="center"> StoreKeeper </th>
                                        <th class="center"> StoreCode </th>
                                        <th class="center"> CountDate </th>
                                        <th class="center"> CountedBy </th>
                                        <th class="center"> ApprovedBy </th>
                                        <th class="center"> Action </th>
                                    </tr>
                                </thead>
                                @foreach (var obj in Model)
                                {
                                    <tbody>
                                        <tr class="odd gradeX">
                                            <td class="table-img center">
                                                <a asp-controller="Inventory" asp-action="GRNInvoice" asp-route-id="@obj.CountID" )"><img src="~/images/inventory/2038147.png" alt=""></a>

                                            </td>
                                            <td class="center">@obj.StoreCode</td>
                                            <td class="center">@obj.StoreKeeper</td>
                                            <td class="center">@obj.StoreCode</td>
                                            <td class="center">@obj.CountDate.Value.ToString("MMM-dd-yyyy")</td>
                                            <td class="center">@obj.CountedBy</td>
                                            <td class="center">@obj.ApprovedBy</td>

                                            <td class="center">
                                                @* <a href="#" class="btn btn-tbl-edit">
                                        <i class="material-icons">create</i>
                                        </a>*@
                                                <form asp-action="CODelete" asp-route-id="@obj.CountID" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                                                    <input type="hidden" asp-for="@obj.CountID" />
                                                    <button type="submit" value="Delete" class="btn btn-tbl-delete">
                                                        <i class="material-icons">delete_forever</i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>

                                    </tbody>
                                }

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}