Models/EmployeeStatusChange.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DDU.Models
{
    public class EmployeeStatusChange
    {
        [Key]
        public Guid EmployeeStatusChangeID { get; set; }

        public Guid EmployeeID { get; set; }

        public int StatusType { get; set; }

        public int TerminationType { get; set; }

        public DateTime DateOn { get; set; }

        public DateTime RequestDate { get; set; }

        public string? Remark { get; set; }

        public string? Reason { get; set; }
        

        public string? SessionID { get; set; }

        public string? SessionIP { get; set; }

        public string? SessionMAC { get; set; }

        [NotMapped]
        public List<SelectListItem>? ListStatus { set; get; }

        [NotMapped]
        public string? Status { set; get; }

        [NotMapped]
        public List<SelectListItem>? ListEmployees { set; get; }

        [NotMapped]
        public string? EmployeeName { set; get; }

    }
}

Controllers/EmployeeStatusChangeController.cs
using DDU.Data;
using DDU.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DDU.Controllers
{
    
    public class EmployeeStatusChangeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public EmployeeStatusChangeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {

            IEnumerable<vw_EmployeeStatusChange>? vw_EmployeeStatusChange = _db.vw_EmployeeStatusChange.ToList();

            return View(vw_EmployeeStatusChange);
        }

        [HttpGet]
        public IActionResult AddEmployeeStatusChanges()
        {


            EmployeeStatusChange mymodel = new EmployeeStatusChange();

            mymodel.ListStatus = new List<SelectListItem>();
            var datadep = _db.tblLookup.Select(z => z).Where(s => s.Parent == "1").ToList();
            mymodel.ListStatus.Add(new SelectListItem
            {
                Text = "Select Status",
                Value = ""

            });
            foreach (var item in datadep)
            {
                mymodel.ListStatus.Add(new SelectListItem
                {
                    Text = item.Description,
                    Value = Convert.ToString(item.Id)

                });
            }
            mymodel.ListEmployees = new List<SelectListItem>();
            var data = _db.employeeRegistration.ToList();
            mymodel.ListEmployees.Add(new SelectListItem
            {
                Text = "Select Employee",
                Value = ""

            });
            foreach (var item in data)
            {
                mymodel.ListEmployees.Add(new SelectListItem
                {
                    Text = String.Format("{0} {1}", item.FirstName, item.MiddleName),
                    Value = Convert.ToString(item.EmployeeID)

                });
            }


            return View(mymodel);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEmployeeStatusChangesAsync(EmployeeStatusChange obj)
        {
            obj.EmployeeStatusChangeID = Guid.NewGuid();
            if (ModelState.IsValid)
            {
                _db.employeeStatusChange.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "EmployeeStatusChange Create successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(Guid? id)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }
            EmployeeStatusChange mymodel = new EmployeeStatusChange();

            mymodel = _db.employeeStatusChange.Find(id);

            mymodel.ListStatus = new List<SelectListItem>();
            var datadep = _db.tblLookup.Select(z => z).Where(s => s.Parent == "1").ToList();
            mymodel.ListStatus.Add(new SelectListItem
            {
                Text = "Select Status",
                Value = ""

            });
            foreach (var item in datadep)
            {
                mymodel.ListStatus.Add(new SelectListItem
                {
                    Text = item.Description,
                    Value = Convert.ToString(item.Id)

                });
            }

            mymodel.ListEmployees = new List<SelectListItem>();
            var data = _db.employeeRegistration.ToList();
            mymodel.ListEmployees.Add(new SelectListItem
            {
                Text = "Select Employee",
                Value = ""

            });
            foreach (var item in data)
            {
                mymodel.ListEmployees.Add(new SelectListItem
                {
                    Text = String.Format("{0} {1}", item.FirstName, item.MiddleName),
                    Value = Convert.ToString(item.EmployeeID)

                });
            }

            return View(mymodel);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EmployeeStatusChange obj)
        {
            _db.employeeStatusChange.Update(obj);
            _db.SaveChanges();
            TempData["success"] = "Edit successfully";
            return RedirectToAction("Index");
        }

        // POST: Transfers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid? id)
        {
            var statusModel = await _db.employeeStatusChange.FindAsync(id);
            _db.employeeStatusChange.Remove(statusModel);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Views/EmployeeStatusChange/AddEmployeeStatusChanges.cshtml
@{
    ViewData["Title"] = "Add EmployeeStatusChange Jobs";
    ViewData["name"] = "employees";
    ViewData["category"] = "hr";
    //SelectList positions = ViewBag.PositionId;
    //var currentlySelectedIndex = 0; // Currently selected index (usually will come from model)
}
@model EmployeeStatusChange
@section Content {
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Termination/Rehiring</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="../../index.html">
                                <i class="fas fa-home"></i> Termination
                            </a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="#" onclick="return false;">Termination/Rehiring</a>
                        </li>
                        <li class="breadcrumb-item active">Add Termination/Rehiring</li>
                    </ul>
                </div>
            </div>
         </div>

        
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                <strong>Add</strong> Termination/Rehiring
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu float-end" style="">
                                        <li>
                                            <a href="javascript:void(0);">Action</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0);">Another action</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0);">Something else here</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <form method="post" enctype="multipart/form-data">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="row clearfix">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                @Html.DropDownListFor(model => model.TerminationType, new SelectList(Model.ListStatus, "Value", "Text"),new{@class="col-12 m-t-20 p-l-0"})

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                @Html.DropDownListFor(model => model.EmployeeID, new SelectList(Model.ListEmployees, "Value", "Text"),new{@class="col-12 m-t-20 p-l-0"})

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <div class="row clearfix">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <label for="email_address">Request Date</label>
                                            <input type="text" value="@DateTime.Now.ToShortDateString()" class="flatpickr"
                                               placeholder="RequestDate" asp-for="RequestDate" onfocus="(this.type='Date')" />
                                            @*<input asp-for="RequestDate" type="text" class=flatpickr data-enable-time=true data-allow-input=true" placeholder=@DateTime.Now.ToShortDateString() onfocus="(this.type='Date')" />*@
                                                <span asp-validation-for="RequestDate" class="text-danger"></span>

                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">

                                        <label for="email_address">Date On</label>                                      
                                        <input asp-for="DateOn" type="text" value="@DateTime.Now.ToShortDateString()" class="flatPicker" placeholder="DateOn" onfocus="(this.type='Date')" />
                                        <span asp-validation-for="DateOn" class="text-danger"></span>

                                    </div>
                                </div>
                            </div>
@*                                <div class="row clearfix">

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input asp-for="RequestDate" type="text" class="form-control datetimepicker flatpickr-input" placeholder="Request Date" onfocus="(this.type='Date')" />
                                                <span asp-validation-for="RequestDate" class="text-danger"></span>

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                    <div class="form-group">

                                            <input asp-for="DateOn" type="text" class="form-control datetimepicker flatpickr-input" placeholder="Date On" onfocus="(this.type='Date')" />
                                            <span asp-validation-for="DateOn" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>*@
                                <div class="row clearfix">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input asp-for="Reason" class="form-control" placeholder="Reason" />
                                                <span asp-validation-for="Reason" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group form-float">

                                            <div class="form-line">
                                                <input asp-for="Remark" class="form-control" placeholder="Remark" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12 p-t-20 text-center">
                                    <button type="submit" class="btn btn-primary waves-effect m-r-15">Submit</button>
                                    <button href="@Url.Action("Index","EmployeeStatusChange")" type="button" class="btn btn-danger waves-effect">Cancel</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
}
    @section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Views/EmployeeStatusChange/Edit.cshtml
@{
    ViewData["Title"] = "Add EmployeeStatusChange Jobs";
    ViewData["name"] = "employees";
    ViewData["category"] = "hr";
    //SelectList positions = ViewBag.PositionId;
    //var currentlySelectedIndex = 0; // Currently selected index (usually will come from model)
}
@model EmployeeStatusChange
@section Content {
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Termination/Rehiring</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="../../index.html">
                                <i class="fas fa-home"></i> Termination
                            </a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="#" onclick="return false;">Termination/Rehiring</a>
                        </li>
                        <li class="breadcrumb-item active">Edit Termination/Rehiring</li>
                    </ul>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <strong>Add</strong> Termination/Rehiring
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu float-end" style="">
                                    <li>
                                        <a href="javascript:void(0);">Action</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">Another action</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">Something else here</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <form method="post" enctype="multipart/form-data">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input asp-for="EmployeeStatusChangeID" hidden />
                            <div class="row clearfix">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            @Html.DropDownListFor(model => model.TerminationType, new SelectList(Model.ListStatus, "Value", "Text"),new{@class="col-12 m-t-20 p-l-0"})

                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            @Html.DropDownListFor(model => model.EmployeeID, new SelectList(Model.ListEmployees, "Value", "Text"),new{@class="col-12 m-t-20 p-l-0"})

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input asp-for="RequestDate" type="text" class="form-control datetimepicker flatpickr-input" placeholder="Request Date" onfocus="(this.type='Date')" />
                                            <span asp-validation-for="RequestDate" class="text-danger"></span>

                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group focused">

                                        <input asp-for="DateOn" type="text" class="form-control datetimepicker flatpickr-input" placeholder="Date On" onfocus="(this.type='Date')" />
                                        <span asp-validation-for="DateOn" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input asp-for="Reason" class="form-control" placeholder="Reason" />
                                            <span asp-validation-for="Reason" class="text-danger"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group form-float">

                                        <div class="form-line">
                                            <input asp-for="Remark" class="form-control" placeholder="Remark" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12 p-t-20 text-center">
                                <button type="submit" class="btn btn-primary waves-effect m-r-15">Submit</button>
                                <button href="@Url.Action("Index","EmployeeStatusChange")" type="button" class="btn btn-danger waves-effect">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

Views/EmployeeStatusChange/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["name"] = "TerminationRehire";
    ViewData["category"] = "hr";
}
@model IEnumerable<vw_EmployeeStatusChange>
@section Content{
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Termination/Rehire</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="#">
                                <i class="fas fa-home"></i> HR
                            </a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="#" onClick="return false;">Termination/Rehire</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2 style="display:flex; justify-content: space-between; margin-right: 20px;">
                            <strong>Termination/Rehire</strong>
                            <button onclick="location.href='@Url.Action("AddEmployeeStatusChanges","EmployeeStatusChange")'" class="btn btn-sucess d-flex align-items-center"><i class="fa fa-plus-circle me-2"></i>Add Termination</button>
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-bs-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu float-end">
                                    <li>
                                        <a href="javascript:void(0);">Action</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">Another action</a>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0);">Something else here</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example contact_list">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th> Employee Name</th>
                                        <th> Request Date </th>
                                        <th> Date On </th>
                                        <th> Status </th>
                                        <th> Reason </th>
                                        <th> Action </th>
                                    </tr>
                                </thead>
                                <tbody class="text-left">
                                @foreach (var obj in Model)
                                {
                                    <tr>
                                        <td class="table-img center">
                                            <a href="@Url.Action("Profile","Home")"><img src="~/assets/images/user/employee.jpg" alt=""></a>
                                        </td>
                                            <td>@String.Format("{0} {1}",obj.FirstName,obj.MiddleName)</td>
                                            @if (obj.RequestDate.HasValue)
                                            {

                                                <td class="center">@obj.RequestDate.Value.ToString("MMM-dd-yyyy")</td>
                                            }
                                            else
                                            {
                                                <td></td>
                                            }
                                            @if (obj.DateOn.HasValue)
                                            {

                                                <td class="center">@obj.DateOn.Value.ToString("MMM-dd-yyyy")</td>
                                            }
                                            else
                                            {
                                                <td></td>
                                            }                                       
                                        
                                        <td>@obj.StatusChange</td>
                                        <td>@obj.Reason</td>
                                        <td>
                                            <a asp-controller="EmployeeStatusChange" asp-action="Edit" asp-route-id="@obj.EmployeeStatusChangeID" class="btn btn-tbl-edit">
                                                <i class="material-icons">create</i>
                                            </a>
                                                <form asp-action="Delete" asp-route-id="@obj.EmployeeStatusChangeID" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">

                                                    <button type="submit" value="Delete" class="btn btn-tbl-delete">
                                                        <i class="material-icons">delete_forever</i>
                                                    </button>
                                                </form>
                                        </td>
                                    </tr>                               
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}