Controllers/LeaveController.cs
using DDU.Data;
using DDU.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Reflection;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace DDU.Controllers
{
    public class LeaveController : Controller
    {
        private readonly ApplicationDbContext _db;
        private IHostingEnvironment _he;

        public LeaveController(ApplicationDbContext db, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
        }

        public IActionResult Index()
        {
            IEnumerable<TblLeaveRequest> leaveFromDb = _db.tblLeaveRequest;
            var leaveRequests = leaveFromDb.Where(e=>e.IsRemoved == 0).ToList();
            var employees = _db.employeeRegistration;
            var leaveTypes = _db.tblLeaveType.ToList().Where(e=> e.IsDeleted == 0);
            ViewData["Employees"] = employees.ToList();
            ViewData["LeaveTypes"] = leaveTypes.ToList();
            
            return View(leaveRequests);
        }

        [HttpPost]
        public IActionResult AddLeaveRequest(TblLeaveRequest request)
        {
            if (request != null)
            {
                _db.tblLeaveRequest.Add(request);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Balance()
        {
            return View();
        }

        public IActionResult Types()
        {
            IEnumerable<TblLeaveType> leaveTypes = _db.tblLeaveType;
            var allLeaveTypes = leaveTypes.ToList().Where(e => e.IsDeleted == 0);
            return View(allLeaveTypes);
        }

        [HttpPost]
        public ActionResult AddLeaveType(TblLeaveType lt)
        {
            if(lt.LeaveTypeId != 0)
            {
                _db.tblLeaveType.Update(lt);
            }
            else
            {
                _db.tblLeaveType.Add(lt);
            }
            _db.SaveChanges();
            return RedirectToAction("Types");
        }

        public IActionResult DeleteTypes(int leaveTypeId)
        {
            var leaveTypes = _db.tblLeaveType.Find(leaveTypeId);
            if(leaveTypes != null)
            {
                leaveTypes.IsDeleted = 1;
                _db.tblLeaveType.Update(leaveTypes);
                _db.SaveChanges();
            }
            return RedirectToAction("Types");
        }

        public IActionResult Approve(Guid LeaveRequestId)
        {
            var leaveRequests = _db.tblLeaveRequest;
            var approvedLeaveRequest = leaveRequests.FirstOrDefault(e => e.EmpLeaveRequestId == LeaveRequestId);
            if(approvedLeaveRequest != null)
            {
                approvedLeaveRequest.ApproveDate = DateTime.Now;
                approvedLeaveRequest.ApprovedBy = "Admin";
                _db.tblLeaveRequest.Update(approvedLeaveRequest);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Leave/Index.cshtml
@model IEnumerable<TblLeaveRequest>
@{
    ViewData["Title"] = "Home Page";
    ViewData["name"] = "leave";
    ViewData["category"] = "hr";
}
@section Content {
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Leave Request</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="#">
                                <i class="fas fa-home"></i> HR
                            </a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="#" onClick="return false;">Leave</a>
                        </li>
                        <li class="breadcrumb-item active">Leave Request</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header sectionHeader">
                        <div>
                            <button type="button" onclick="location.href='@Url.Action("Index","Leave")'" class="btn btn-secondary waves-effect active">Leave Request</button>
                            <button type="button" onclick="location.href='@Url.Action("Types","Leave")'" class="btn btn-secondary waves-effect">Leave Types</button>
                        </div>
                        <div>
                            <button data-bs-toggle="modal" data-bs-target="#addLeaveRequest" class="btn btn-sucess d-flex align-items-center"><i class="fa fa-plus-circle me-2"></i> Add Leave Request</button>
                        </div>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example contact_list">
                                <thead>
                                    <tr>
                                        <th class="center">#</th>
                                        <th class="center"> Name </th>
                                        <th class="center"> Request Date </th>
                                        <th class="center"> Status </th>
                                        <th class="center"> Leave From </th>
                                        <th class="center"> Leave To </th>
                                        <th class="center"> Leave Type </th>
                                        <th class="center"> Action </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var obj in Model)
                                    {
                                        <tr class="odd gradeX">
                                            <td class="table-img center">
                                                <img src=@obj.Employee.Image1Path style="width:50px;height:50px;" alt="">
                                            </td>
                                            <td class="center">@obj.Employee.FirstName @obj.Employee.MiddleName @obj.Employee.LastName</td>
                                            <td class="center">@obj.RequestDate</td>
                                            @if (obj.ApproveDate == null)
                                            {
                                                <td class="center">
                                                    <div class="badge col-red">Requested</div>
                                                </td>
                                            }
                                            else
                                            {
                                                <td class="center">
                                                    <div class="badge col-green">Approved</div>
                                                </td>
                                            }
                                            <td class="center">@obj.FromDate</td>
                                            <td class="center">@obj.ToDate</td>
                                            <td class="center">@obj.LeaveType.LeaveType</td>
                                            <td class="center">
                                                <a class="circleBorder" onclick="return WarnApproval()" href="@Url.Action("Approve","Leave", new{ LeaveRequestId = obj.EmpLeaveRequestId })">
                                                    <i class="fa fa-check"></i>
                                                </a>
                                                <a data-bs-toggle="modal" data-bs-target="#addLeaveRequest" onclick="populateRequest('@obj.EmpLeaveRequestId', '@obj.ReferenceNo','@obj.Employee.EmployeeID','@obj.LeaveType.LeaveTypeId','@obj.FromDate','@obj.ToDate','@obj.ResumeWorkOn','@obj.AvailableDays','@obj.NoOfRequestedDays','@obj.RemainingDays','@obj.LeaveBalance','@obj.Reason')" class="btn btn-tbl-edit">
                                                    <i class="material-icons">create</i>
                                                </a>
                                                <a href="#" class="btn btn-tbl-delete">
                                                    <i class="material-icons">delete_forever</i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="addLeaveRequest" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <form method="post" action="@Url.Action("AddLeaveRequest","Leave")">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Leave Request</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <label class="label form-label">Reference Number</label>
                        <input type="text" name="ReferenceNo" id="ReferenceNo" class="form-control" placeholder="Reference Number" />
                    </div>
                    <div class="modal-body">
                        <select name="EmployeeID" id="EmployeeID">
                            <option>Select Employee</option>
                            @foreach (var emp in ViewData["Employees"] as List<DDU.Models.EmployeeRegistration>)
                            {
                                <option value="@emp.EmployeeID">@emp.FirstName @emp.MiddleName @emp.LastName</option>
                            }
                        </select>
                    </div><div class="modal-body">
                        <select name="LeaveTypeId" id="LeaveTypeId">
                            <option>Select Leave Type</option>
                            @foreach (var emp in ViewData["LeaveTypes"] as List<DDU.Models.TblLeaveType>)
                            {
                                <option value="@emp.LeaveTypeId">@emp.LeaveType</option>
                            }
                        </select>
                    </div>
                    <div class="modal-body">
                        <label class="label form-label">From Date</label>
                        <input type="datetime-local" name="FromDate" id="FromDate" class="form-control"/>
                    </div>
                    <div class="modal-body">
                        <label class="label form-label">To Date</label>
                        <input type="datetime-local" name="ToDate" id="ToDate" class="form-control"/>
                        <input type="hidden" name="RequestDate" value="@DateTime.Now" />
                    </div>
                    <div class="modal-body">
                        <label class="label form-label">Resume Workon</label>
                        <input type="datetime-local" name="ResumeWorkOn" id="ResumeWorkOn" class="form-control" />
                    </div>
                    <div class="modal-body">
                        <label class="label form-label">Available Days</label>
                        <input type="text" name="AvailableDays" id="AvailableDays" class="form-control" placeholder="Available Days" />
                    </div>
                    <div class="modal-body">
                        <label class="label form-label">No Of Requested Days</label>
                        <input type="text" name="NoOfRequestedDays" id="NoOfRequestedDays" class="form-control" placeholder="No Of Requested Days" />
                    </div>
                    <div class="modal-body">
                        <label class="label form-label">Remaining Days</label>
                        <input type="text" name="RemainingDays" id="RemainingDays" class="form-control" placeholder="Remaining Days" />
                        <input type="hidden" name="EmpLeaveRequestId" id="EmpLeaveRequestId" />
                    </div>
                    <div class="modal-body">
                        <label class="label form-label">Leave Balance</label>
                        <input type="text" name="LeaveBalance" id="LeaveBalance" class="form-control" placeholder="Leave Balance" />
                    </div>
                    <div class="modal-body">
                        <label class="label form-label">Reason</label>
                        <input type="text" name="Reason" id="Reason" class="form-control" placeholder="Reason" />
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <script>
        function WarnApproval() {
            var check = confirm("Are you sure you want to approve this leave Request?");
            if (check) {
                return true;
            }
            return false;
        }

        function populateRequest(EmpLeaveRequestId, ReferenceNo, EmployeeID, LeaveTLeaveTypeId, FromDate, ToDate, ResumeWorkOn, AvailableDays, NoOfRequestedDays, RemainingDays, LeaveBalance, Reason){
            $("#EmpLeaveRequestId").val(EmpLeaveRequestId);
            $("#ReferenceNo").val(ReferenceNo);
            $("#EmployeeID").val(EmployeeID);
            var objSelect = document.getElementById("EmployeeID");
            setSelectedValue(objSelect, EmployeeID);
            $("#LeaveTypeId").val(LeaveTypeId);
            $("#FromDate").val(ToCustomDate(new Date(FromDate)));
            $("#ToDate").val(ToCustomDate(new Date(ToDate)));
            $("#ResumeWorkOn").val(ToCustomDate(new Date(ResumeWorkOn)));
            $("#AvailableDays").val(AvailableDays);
            $("#NoOfRequestedDays").val(NoOfRequestedDays);
            $("#RemainingDays").val(RemainingDays);
            $("#LeaveBalance").val(LeaveBalance);
            $("#Reason").val(Reason);
        }

        function ToCustomDate(d){
            var dateString = d.getFullYear() + "-" + ("0" + d.getDate()).slice(-2) + "-" + ("0" + (d.getMonth() + 1)).slice(-2) + " " +
                ("0" + d.getHours()).slice(-2) + ":" + ("0" + d.getMinutes()).slice(-2);
            return dateString;
        }

        function setSelectedValue(selectObj, valueToSet) {
            for (var i = 0; i < selectObj.options.length; i++) {
                if (selectObj.options[i].text == valueToSet) {
                    selectObj.options[i].selected = true;
                    return;
                }
            }
        }
    </script>
}

Views/Leave/Types.cshtml
@model IEnumerable<TblLeaveType>
@{
    ViewData["Title"] = "Home Page";
    ViewData["name"] = "HRSettings";
    ViewData["category"] = "hr";
    int count = 1;
}

@section Content{
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Leave Type</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="#">
                                <i class="fas fa-home"></i> HR
                            </a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="#" onClick="return false;">Leave</a>
                        </li>
                        <li class="breadcrumb-item active">Leave Type</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header sectionHeader">
                        <div>
                            <button type="button" onclick="location.href='@Url.Action("Index","Leave")'" class="btn btn-secondary waves-effect">Leave Request</button>
                            <button type="button" onclick="location.href='@Url.Action("Types","Leave")'" class="btn btn-secondary waves-effect active">Leave Types</button>
                        </div>
                        <button data-bs-toggle="modal" data-bs-target="#addLeaveType" class="btn btn-sucess d-flex align-items-center"><i class="fa fa-plus-circle me-2"></i> Add Leave Type</button>

                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example contact_list">
                                <thead>
                                    <tr>
                                        <th> # </th>
                                        <th> Name </th>
                                        <th> No of Days </th>
                                        <th> Is Paid</th>
                                        <th> Condition </th>
                                        <th> Action </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var obj in Model)
                                    {
                                        if (obj != null)
                                        {
                                            <tr class="odd gradeX">
                                                <td>@count</td>
                                                <td>@obj.LeaveType</td>
                                                <td>
                                                    <div class="badge col-green">@obj.NoOfDays</div>
                                                </td>
                                                <td>@obj.Pay</td>
                                                @if(@obj.Condition != null){
                                                    <td>@obj.Condition</td>
                                                }
                                                else{
                                                    <td class="ml-1">-</td>
                                                }
                                                <td>
                                                    <button class="btn tblActnBtn" onclick="populateLeaveTypes('@obj.LeaveTypeId','@obj.LeaveType','@obj.Pay','@obj.NoOfDays','@obj.Condition','@obj.Description')" data-bs-toggle="modal" data-bs-target="#addLeaveType">
                                                        <i class="material-icons">mode_edit</i>
                                                    </button>
                                                    <a onclick="return WarnDelete()" href="@Url.Action("DeleteTypes","Leave", new{ leaveTypeId = obj.LeaveTypeId })" class="btn btn-tbl-delete">
                                                        <i class="material-icons">delete</i>
                                                    </a>
                                                </td>
                                            </tr>
                                            count += 1;
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="addLeaveType" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <form method="post" action="@Url.Action("AddLeaveType","Leave")">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Leave Type</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <input type="text" name="LeaveType" id="LeaveType" class="form-control" placeholder="Input leave type" />
                    </div>
                    <div class="modal-body">
                        <select name="Pay" id="Pay">
                            <option value="Yes">Pay</option>
                            <option value="No">No Pay</option>
                        </select>
                    </div>
                    <div class="modal-body">
                        <input type="text" name="NoOfDays" id="NoOfDays" class="form-control" placeholder="Number of Days" />
                    </div>
                    <div class="modal-body">
                        <input type="text" class="form-control" id="Condition" name="Condition" placeholder="Input Conditions" />
                        <input type="hidden" name="LeaveTypeId" id="LeaveTypeId" value="0" />
                        <input type="hidden" name="IsDeleted" id="IsDeleted" value="0" />
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <script>
        function populateLeaveTypes(LeaveTypeId, LeaveType, Pay, NoOfDays, Condition, Description) {
            $("#LeaveTypeId").val(LeaveTypeId);
            $("#LeaveType").val(LeaveType);
            $("#Pay").val(Pay);
            $("#NoOfDays").val(NoOfDays);
            $("#Condition").val(Condition);
            $("#Description").val(Description);
        }

        function WarnDelete() {
            var check = confirm("Are you sure you want to delete");
            if (check) {
                return true;
            }
            return false;
        }
    </script>
}